# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-12 06:25
from __future__ import unicode_literals

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vrblog', '0006_vrblogcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vrblogcategory',
            options={'verbose_name_plural': 'vrblog categories'},
        ),
        migrations.AddField(
            model_name='vrblogpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='vrblog.VrblogCategory'),
        ),
    ]
