# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vrblog', '0008_auto_20170820_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrblogpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='vrblogpagegalleryimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
