# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('vrblog', '0010_auto_20170821_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='VrblogIndexPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.TextField(verbose_name='Text')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vrblogindexpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
        migrations.AddField(
            model_name='vrblogindexpagegalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_gallery_images', to='vrblog.VrblogIndexPage'),
        ),
    ]
