# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('vrblog', '0012_vrblogindexpage_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vrblogindexpage',
            old_name='main_image',
            new_name='equirectangular_image',
        ),
        migrations.AddField(
            model_name='vrblogpage',
            name='equirectangular_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
